# Generated by Django 4.1.4 on 2023-01-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
