# Generated by Django 4.1.4 on 2023-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_remove_projects_image_projects_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='date',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=1, upload_to='proje/'),
            preserve_default=False,
        ),
    ]
