# Generated by Django 4.1.4 on 2023-01-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_remove_projects_date_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
    ]
